### ISSUE TITLE
Syntax in package is too new for Node 14

### ISSUE THREAD

**Issue by jakebailey** [nujarum/resolve-esm#24]
I was testing out your package as an alternative to `import-meta-resolve`; I got errors when trying to call the resolve function as `dist/index.mjs` contains `??=`, which isn't syntax that's legal in Node 14.

Can you retarget your `tsconfig` or rollup config (not sure which produces dist) so that Node 14 can use this library?

**Comment by nujarum** [comment]
@jakebailey, thanks for your comment.

I inadvertently forgot about the compatibility with v14.
I will fix it and include it in the next release. Please wait a while.

**Comment by nujarum** [comment]
This issue has been resolved in [v1.2.0](https://www.npmjs.com/package/resolve-esm/v/1.2.0) 🎉
